services:
  app:
    image: ghcr.io/since-98/recipescrud:latest
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
    depends_on:
      - db

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  storage_data:
